// initial-word.tsx

export type Meaning = {
  id: number;
  meaning: string;
};
export type Phrase = {
  meaningId: number;
  languageCode: string;
  phrase: string;
};

export const languageCodeToLanguage: { [key: string]: string } = {
  "ja-JP": "Japanese",
  "en-US": "English(US)",
  "fr-FR": "French",
  "de-DE": "German",
  // "ko-KR": "Korean",
  "zh-CN": "Chinese",
  //  "es-ES": "Spanish",
  // 他の言語コードと対応する言語を追加する
};

export const languageToLanguageCode: { [key: string]: string } = {
  Japanese: "ja-JP",
  "English(US)": "en-US",
  French: "fr-FR",
  German: "de-DE",
  //  Korean: "ko-KR",
  Chinese: "zh-CN",
  //Spanish: "es-ES",
  // 他の言語と対応する言語コードを追加する
};

// 基本的なフレーズ（意味データ）
export const meanings: Meaning[] = [
  { id: 1, meaning: " こんにちは。" },
  { id: 2, meaning: " さようなら。" },
  { id: 3, meaning: " ありがとうございます。" },
  { id: 4, meaning: " お願いします。" },
  { id: 5, meaning: " すみません。" },
  { id: 6, meaning: " ごめんなさい。" },
  { id: 7, meaning: " はい。" },
  { id: 8, meaning: " いいえ。" },
  { id: 9, meaning: " お元気ですか？" },
  { id: 10, meaning: " 元気です、ありがとう。" },
  { id: 11, meaning: " お名前は何ですか？" },
  { id: 12, meaning: " 私の名前は［名前］です。" },
  { id: 13, meaning: " 出身はどこですか？" },
  { id: 14, meaning: " 私は［国名］出身です。" },
  { id: 15, meaning: " 今何時ですか？" },
  { id: 16, meaning: " 手伝ってくれますか？" },
  { id: 17, meaning: " わかりません。" },
  { id: 18, meaning: " これはいくらですか？" },
  { id: 19, meaning: " トイレはどこですか？" },
  { id: 20, meaning: " 医者が必要です。" },
  { id: 21, meaning: " 助けて！" },
  { id: 22, meaning: " 道に迷いました。" },
  { id: 23, meaning: " メニューをください。" },
  { id: 24, meaning: " ［料理］を注文したいです。" },
  { id: 25, meaning: " これは辛いですか？" },
  { id: 26, meaning: " 乾杯！" },
  { id: 27, meaning: " 最寄りの駅はどこですか？" },
  { id: 28, meaning: " ［目的地］行きの切符はいくらですか？" },
  { id: 29, meaning: " 私の写真を撮ってもらえますか？" },
  { id: 30, meaning: " ここが大好きです。" },
  { id: 31, meaning: " おすすめのレストランを教えてください。" },
  { id: 32, meaning: " 自慢の料理は何ですか？" },
  { id: 33, meaning: " 近くに薬局はありますか？" },
  { id: 34, meaning: " ［場所］はどれくらいの距離ですか？" },
  { id: 35, meaning: " もっとゆっくり話してもらえますか？" },
  { id: 36, meaning: " お土産はどこで買えますか？" },
  { id: 37, meaning: " 割引してもらえますか？" },
  { id: 38, meaning: " ここで無料のWi-Fiはありますか？" },
  { id: 39, meaning: " 今日の天気はどうですか？" },
  { id: 40, meaning: " 地元の観光スポットを教えてもらえますか？" },
  { id: 41, meaning: " タクシーを呼んでください。" },
  { id: 42, meaning: " 空港までいくらですか？" },
  { id: 43, meaning: " 予約してあります。" },
  { id: 44, meaning: " 朝食は含まれていますか？" },
  { id: 45, meaning: " [時間]にモーニングコールをお願いします。" },
  { id: 46, meaning: " 部屋に金庫はありますか？" },
  { id: 47, meaning: " ［観光名所］は何時にオープン/クローズしますか？" },
  { id: 48, meaning: " おすすめの散歩スポットを教えてください。" },
  { id: 49, meaning: " ［場所］に行きたいです。" },
  { id: 50, meaning: " ここで泳いでも大丈夫ですか？" },
  { id: 51, meaning: " ［目的地］へはどう行けばいいですか？" },
  { id: 52, meaning: " それをメモしてもらえますか？" },
  { id: 53, meaning: " もっと水をもらえますか？" },
  { id: 54, meaning: " 街を移動するのに最適な方法は何ですか？" },
  { id: 55, meaning: " 英語を話せますか？" },
  { id: 56, meaning: " ［食材］は食べられません。" },
  { id: 57, meaning: " 郵便局はどこにありますか？" },
  { id: 58, meaning: " 電車/バスは何番線から出発しますか？" },
  { id: 59, meaning: " 試着してもいいですか？" },
  { id: 60, meaning: " 地図はありますか？" },
  { id: 61, meaning: " タクシーを呼んでくれますか？" },
  { id: 62, meaning: " 近くにATMはありますか？" },
  { id: 63, meaning: " ［食べ物/アレルゲン］にアレルギーがあります。" },
  { id: 64, meaning: " 地図で示してもらえますか？" },
  { id: 65, meaning: " そこまでどれくらいかかりますか？" },
  { id: 66, meaning: " 駐車場はありますか？" },
  { id: 67, meaning: " 領収書をもらえますか？" },
  { id: 68, meaning: " 予約していません。" },
  { id: 69, meaning: " ベジタリアン向けのオプションはありますか？" },
  { id: 70, meaning: " お会計をお願いします。" },
  { id: 71, meaning: " 空港への最適な方法は何ですか？" },
  { id: 72, meaning: " 近くにガソリンスタンドはありますか？" },
  { id: 73, meaning: " クレジットカードで支払えますか？" },
  { id: 74, meaning: " チェックアウトの時間は何時ですか？" },
  { id: 75, meaning: " 禁煙ルームをお願いできますか？" },
  { id: 76, meaning: " ［通貨］の為替レートはいくらですか？" },
  { id: 77, meaning: " おすすめのショッピングスポットを教えてください。" },
  { id: 78, meaning: " 大使館に行く必要があります。" },
  { id: 79, meaning: " 英語のメニューはありますか？" },
  { id: 80, meaning: " 興味ありません。" },
  { id: 81, meaning: " バスはどこで乗れますか？" },
  { id: 82, meaning: " もっとゆっくり話してください。" },
  { id: 83, meaning: " ［観光名所］への最適な方法は何ですか？" },
  { id: 84, meaning: " 同じものを注文します。" },
  { id: 85, meaning: " 駅にはどうやって行きますか？" },
  { id: 86, meaning: " 近くに公衆電話はありますか？" },
  { id: 87, meaning: " 気分が悪いです。" },
  { id: 88, meaning: " ホテルへの最適な方法は何ですか？" },
  { id: 89, meaning: " もっと大きな声で話してもらえますか？" },
  { id: 90, meaning: " ［場所］を探しています。" },
  { id: 91, meaning: " Wi-Fiのパスワードは何ですか？" },
  { id: 92, meaning: " 窓側の席に座れますか？" },
  { id: 93, meaning: " これはおいしい！" },
  { id: 94, meaning: " おすすめのホテルを教えてください。" },
  { id: 95, meaning: " 中心地への最適な方法は何ですか？" },
  { id: 96, meaning: " ［ドリンク］を一杯ください。" },
  { id: 97, meaning: " エレベーターはありますか？" },
  { id: 98, meaning: " 追加の毛布をお願いします。" },
  { id: 99, meaning: " 明日の天気予報はどうですか？" },
  { id: 100, meaning: " 助けていただきありがとうございます。" },
];

// 基本的なフレーズに対する他言語データ
export const initialPhrases: Phrase[] = [
  // 日本語
  { meaningId: 1, languageCode: "ja-JP", phrase: " こんにちは。" },
  { meaningId: 2, languageCode: "ja-JP", phrase: " さようなら。" },
  { meaningId: 3, languageCode: "ja-JP", phrase: " ありがとうございます。" },
  { meaningId: 4, languageCode: "ja-JP", phrase: " お願いします。" },
  { meaningId: 5, languageCode: "ja-JP", phrase: " すみません。" },
  { meaningId: 6, languageCode: "ja-JP", phrase: " ごめんなさい。" },
  { meaningId: 7, languageCode: "ja-JP", phrase: " はい。" },
  { meaningId: 8, languageCode: "ja-JP", phrase: " いいえ。" },
  { meaningId: 9, languageCode: "ja-JP", phrase: " お元気ですか？" },
  { meaningId: 10, languageCode: "ja-JP", phrase: " 元気です、ありがとう。" },
  { meaningId: 11, languageCode: "ja-JP", phrase: " お名前は何ですか？" },
  { meaningId: 12, languageCode: "ja-JP", phrase: " 私の名前は［名前］です。" },
  { meaningId: 13, languageCode: "ja-JP", phrase: " 出身はどこですか？" },
  { meaningId: 14, languageCode: "ja-JP", phrase: " 私は［国名］出身です。" },
  { meaningId: 15, languageCode: "ja-JP", phrase: " 今何時ですか？" },
  { meaningId: 16, languageCode: "ja-JP", phrase: " 手伝ってくれますか？" },
  { meaningId: 17, languageCode: "ja-JP", phrase: " わかりません。" },
  { meaningId: 18, languageCode: "ja-JP", phrase: " これはいくらですか？" },
  { meaningId: 19, languageCode: "ja-JP", phrase: " トイレはどこですか？" },
  { meaningId: 20, languageCode: "ja-JP", phrase: " 医者が必要です。" },
  { meaningId: 21, languageCode: "ja-JP", phrase: " 助けて！" },
  { meaningId: 22, languageCode: "ja-JP", phrase: " 道に迷いました。" },
  { meaningId: 23, languageCode: "ja-JP", phrase: " メニューをください。" },
  {
    meaningId: 24,
    languageCode: "ja-JP",
    phrase: " ［料理］を注文したいです。",
  },
  { meaningId: 25, languageCode: "ja-JP", phrase: " これは辛いですか？" },
  { meaningId: 26, languageCode: "ja-JP", phrase: " 乾杯！" },
  { meaningId: 27, languageCode: "ja-JP", phrase: " 最寄りの駅はどこですか？" },
  {
    meaningId: 28,
    languageCode: "ja-JP",
    phrase: " ［目的地］行きの切符はいくらですか？",
  },
  {
    meaningId: 29,
    languageCode: "ja-JP",
    phrase: " 私の写真を撮ってもらえますか？",
  },
  { meaningId: 30, languageCode: "ja-JP", phrase: " ここが大好きです。" },
  {
    meaningId: 31,
    languageCode: "ja-JP",
    phrase: " おすすめのレストランを教えてください。",
  },
  { meaningId: 32, languageCode: "ja-JP", phrase: " 自慢の料理は何ですか？" },
  { meaningId: 33, languageCode: "ja-JP", phrase: " 近くに薬局はありますか？" },
  {
    meaningId: 34,
    languageCode: "ja-JP",
    phrase: " ［場所］はどれくらいの距離ですか？",
  },
  {
    meaningId: 35,
    languageCode: "ja-JP",
    phrase: " もっとゆっくり話してもらえますか？",
  },
  {
    meaningId: 36,
    languageCode: "ja-JP",
    phrase: " お土産はどこで買えますか？",
  },
  { meaningId: 37, languageCode: "ja-JP", phrase: " 割引してもらえますか？" },
  {
    meaningId: 38,
    languageCode: "ja-JP",
    phrase: " ここで無料のWi-Fiはありますか？",
  },
  { meaningId: 39, languageCode: "ja-JP", phrase: " 今日の天気はどうですか？" },
  {
    meaningId: 40,
    languageCode: "ja-JP",
    phrase: " 地元の観光スポットを教えてもらえますか？",
  },
  {
    meaningId: 41,
    languageCode: "ja-JP",
    phrase: " タクシーを呼んでください。",
  },
  { meaningId: 42, languageCode: "ja-JP", phrase: " 空港までいくらですか？" },
  { meaningId: 43, languageCode: "ja-JP", phrase: " 予約してあります。" },
  { meaningId: 44, languageCode: "ja-JP", phrase: " 朝食は含まれていますか？" },
  {
    meaningId: 45,
    languageCode: "ja-JP",
    phrase: " [時間]にモーニングコールをお願いします。",
  },
  { meaningId: 46, languageCode: "ja-JP", phrase: " 部屋に金庫はありますか？" },
  {
    meaningId: 47,
    languageCode: "ja-JP",
    phrase: " ［観光名所］は何時にオープン/クローズしますか？",
  },
  {
    meaningId: 48,
    languageCode: "ja-JP",
    phrase: " おすすめの散歩スポットを教えてください。",
  },
  { meaningId: 49, languageCode: "ja-JP", phrase: " ［場所］に行きたいです。" },
  {
    meaningId: 50,
    languageCode: "ja-JP",
    phrase: " ここで泳いでも大丈夫ですか？",
  },
  {
    meaningId: 51,
    languageCode: "ja-JP",
    phrase: " ［目的地］へはどう行けばいいですか？",
  },
  {
    meaningId: 52,
    languageCode: "ja-JP",
    phrase: " それをメモしてもらえますか？",
  },
  { meaningId: 53, languageCode: "ja-JP", phrase: " もっと水をもらえますか？" },
  {
    meaningId: 54,
    languageCode: "ja-JP",
    phrase: " 街を移動するのに最適な方法は何ですか？",
  },
  { meaningId: 55, languageCode: "ja-JP", phrase: " 英語を話せますか？" },
  {
    meaningId: 56,
    languageCode: "ja-JP",
    phrase: " ［食材］は食べられません。",
  },
  {
    meaningId: 57,
    languageCode: "ja-JP",
    phrase: " 郵便局はどこにありますか？",
  },
  {
    meaningId: 58,
    languageCode: "ja-JP",
    phrase: " 電車/バスは何番線から出発しますか？",
  },
  { meaningId: 59, languageCode: "ja-JP", phrase: " 試着してもいいですか？" },
  { meaningId: 60, languageCode: "ja-JP", phrase: " 地図はありますか？" },
  {
    meaningId: 61,
    languageCode: "ja-JP",
    phrase: " タクシーを呼んでくれますか？",
  },
  { meaningId: 62, languageCode: "ja-JP", phrase: " 近くにATMはありますか？" },
  {
    meaningId: 63,
    languageCode: "ja-JP",
    phrase: " ［食べ物/アレルゲン］にアレルギーがあります。",
  },
  {
    meaningId: 64,
    languageCode: "ja-JP",
    phrase: " 地図で示してもらえますか？",
  },
  {
    meaningId: 65,
    languageCode: "ja-JP",
    phrase: " そこまでどれくらいかかりますか？",
  },
  { meaningId: 66, languageCode: "ja-JP", phrase: " 駐車場はありますか？" },
  { meaningId: 67, languageCode: "ja-JP", phrase: " 領収書をもらえますか？" },
  { meaningId: 68, languageCode: "ja-JP", phrase: " 予約していません。" },
  {
    meaningId: 69,
    languageCode: "ja-JP",
    phrase: " ベジタリアン向けのオプションはありますか？",
  },
  { meaningId: 70, languageCode: "ja-JP", phrase: " お会計をお願いします。" },
  {
    meaningId: 71,
    languageCode: "ja-JP",
    phrase: " 空港への最適な方法は何ですか？",
  },
  {
    meaningId: 72,
    languageCode: "ja-JP",
    phrase: " 近くにガソリンスタンドはありますか？",
  },
  {
    meaningId: 73,
    languageCode: "ja-JP",
    phrase: " クレジットカードで支払えますか？",
  },
  {
    meaningId: 74,
    languageCode: "ja-JP",
    phrase: " チェックアウトの時間は何時ですか？",
  },
  {
    meaningId: 75,
    languageCode: "ja-JP",
    phrase: " 禁煙ルームをお願いできますか？",
  },
  {
    meaningId: 76,
    languageCode: "ja-JP",
    phrase: " ［通貨］の為替レートはいくらですか？",
  },
  {
    meaningId: 77,
    languageCode: "ja-JP",
    phrase: " おすすめのショッピングスポットを教えてください。",
  },
  {
    meaningId: 78,
    languageCode: "ja-JP",
    phrase: " 大使館に行く必要があります。",
  },
  {
    meaningId: 79,
    languageCode: "ja-JP",
    phrase: " 英語のメニューはありますか？",
  },
  { meaningId: 80, languageCode: "ja-JP", phrase: " 興味ありません。" },
  { meaningId: 81, languageCode: "ja-JP", phrase: " バスはどこで乗れますか？" },
  {
    meaningId: 82,
    languageCode: "ja-JP",
    phrase: " もっとゆっくり話してください。",
  },
  {
    meaningId: 83,
    languageCode: "ja-JP",
    phrase: " ［観光名所］への最適な方法は何ですか？",
  },
  { meaningId: 84, languageCode: "ja-JP", phrase: " 同じものを注文します。" },
  {
    meaningId: 85,
    languageCode: "ja-JP",
    phrase: " 駅にはどうやって行きますか？",
  },
  {
    meaningId: 86,
    languageCode: "ja-JP",
    phrase: " 近くに公衆電話はありますか？",
  },
  { meaningId: 87, languageCode: "ja-JP", phrase: " 気分が悪いです。" },
  {
    meaningId: 88,
    languageCode: "ja-JP",
    phrase: " ホテルへの最適な方法は何ですか？",
  },
  {
    meaningId: 89,
    languageCode: "ja-JP",
    phrase: " もっと大きな声で話してもらえますか？",
  },
  { meaningId: 90, languageCode: "ja-JP", phrase: " ［場所］を探しています。" },
  {
    meaningId: 91,
    languageCode: "ja-JP",
    phrase: " Wi-Fiのパスワードは何ですか？",
  },
  { meaningId: 92, languageCode: "ja-JP", phrase: " 窓側の席に座れますか？" },
  { meaningId: 93, languageCode: "ja-JP", phrase: " これはおいしい！" },
  {
    meaningId: 94,
    languageCode: "ja-JP",
    phrase: " おすすめのホテルを教えてください。",
  },
  {
    meaningId: 95,
    languageCode: "ja-JP",
    phrase: " 中心地への最適な方法は何ですか？",
  },
  {
    meaningId: 96,
    languageCode: "ja-JP",
    phrase: " ［ドリンク］を一杯ください。",
  },
  {
    meaningId: 97,
    languageCode: "ja-JP",
    phrase: " エレベーターはありますか？",
  },
  {
    meaningId: 98,
    languageCode: "ja-JP",
    phrase: " 追加の毛布をお願いします。",
  },
  {
    meaningId: 99,
    languageCode: "ja-JP",
    phrase: " 明日の天気予報はどうですか？",
  },
  {
    meaningId: 100,
    languageCode: "ja-JP",
    phrase: " 助けていただきありがとうございます。",
  },
  // 英語
  { meaningId: 1, languageCode: "en-US", phrase: " Hello" },
  { meaningId: 2, languageCode: "en-US", phrase: " Goodbye" },
  { meaningId: 3, languageCode: "en-US", phrase: " Thank you" },
  { meaningId: 4, languageCode: "en-US", phrase: " Please" },
  { meaningId: 5, languageCode: "en-US", phrase: " Excuse me" },
  { meaningId: 6, languageCode: "en-US", phrase: " Sorry" },
  { meaningId: 7, languageCode: "en-US", phrase: " Yes" },
  { meaningId: 8, languageCode: "en-US", phrase: " No" },
  { meaningId: 9, languageCode: "en-US", phrase: " How are you? " },
  { meaningId: 10, languageCode: "en-US", phrase: " I'm fine, thank you" },
  { meaningId: 11, languageCode: "en-US", phrase: " What's your name? " },
  { meaningId: 12, languageCode: "en-US", phrase: " My name is [name]" },
  { meaningId: 13, languageCode: "en-US", phrase: " Where are you from? " },
  { meaningId: 14, languageCode: "en-US", phrase: " I'm from [country]" },
  { meaningId: 15, languageCode: "en-US", phrase: " What time is it? " },
  { meaningId: 16, languageCode: "en-US", phrase: " Can you help me? " },
  { meaningId: 17, languageCode: "en-US", phrase: " I don't understand" },
  { meaningId: 18, languageCode: "en-US", phrase: " How much is this? " },
  { meaningId: 19, languageCode: "en-US", phrase: " Where is the bathroom? " },
  { meaningId: 20, languageCode: "en-US", phrase: " I need a doctor" },
  { meaningId: 21, languageCode: "en-US", phrase: " Help! " },
  { meaningId: 22, languageCode: "en-US", phrase: " I'm lost" },
  {
    meaningId: 23,
    languageCode: "en-US",
    phrase: " Can I have the menu, please? ",
  },
  { meaningId: 24, languageCode: "en-US", phrase: " I would like [dish]" },
  { meaningId: 25, languageCode: "en-US", phrase: " Is this spicy? " },
  { meaningId: 26, languageCode: "en-US", phrase: " Cheers! " },
  {
    meaningId: 27,
    languageCode: "en-US",
    phrase: " Where is the nearest train station? ",
  },
  {
    meaningId: 28,
    languageCode: "en-US",
    phrase: " How much does a ticket to [destination] cost? ",
  },
  {
    meaningId: 29,
    languageCode: "en-US",
    phrase: " Can you take a photo of me? ",
  },
  { meaningId: 30, languageCode: "en-US", phrase: " I love this place" },
  {
    meaningId: 31,
    languageCode: "en-US",
    phrase: " Can you recommend a good restaurant? ",
  },
  {
    meaningId: 32,
    languageCode: "en-US",
    phrase: " What is your signature dish? ",
  },
  {
    meaningId: 33,
    languageCode: "en-US",
    phrase: " Is there a pharmacy nearby? ",
  },
  { meaningId: 34, languageCode: "en-US", phrase: " How far is [location]? " },
  {
    meaningId: 35,
    languageCode: "en-US",
    phrase: " Can you speak more slowly? ",
  },
  {
    meaningId: 36,
    languageCode: "en-US",
    phrase: " Where can I buy souvenirs? ",
  },
  { meaningId: 37, languageCode: "en-US", phrase: " Can I get a discount? " },
  {
    meaningId: 38,
    languageCode: "en-US",
    phrase: " Is there free Wi-Fi here? ",
  },
  {
    meaningId: 39,
    languageCode: "en-US",
    phrase: " What is the weather like today? ",
  },
  {
    meaningId: 40,
    languageCode: "en-US",
    phrase: " Can you recommend any local attractions? ",
  },
  { meaningId: 41, languageCode: "en-US", phrase: " I need a taxi" },
  {
    meaningId: 42,
    languageCode: "en-US",
    phrase: " How much to the airport? ",
  },
  { meaningId: 43, languageCode: "en-US", phrase: " I have a reservation" },
  { meaningId: 44, languageCode: "en-US", phrase: " Is breakfast included? " },
  {
    meaningId: 45,
    languageCode: "en-US",
    phrase: " Can I have a wake-up call at [time]? ",
  },
  {
    meaningId: 46,
    languageCode: "en-US",
    phrase: " Is there a safe in the room? ",
  },
  {
    meaningId: 47,
    languageCode: "en-US",
    phrase: " What time does the [attraction] open/close? ",
  },
  {
    meaningId: 48,
    languageCode: "en-US",
    phrase: " Can you recommend a good place to take a walk? ",
  },
  {
    meaningId: 49,
    languageCode: "en-US",
    phrase: " I'd like to go to [place]",
  },
  {
    meaningId: 50,
    languageCode: "en-US",
    phrase: " Is it safe to swim here? ",
  },
  {
    meaningId: 51,
    languageCode: "en-US",
    phrase: " How do I get to [destination]? ",
  },
  {
    meaningId: 52,
    languageCode: "en-US",
    phrase: " Can you write that down for me? ",
  },
  {
    meaningId: 53,
    languageCode: "en-US",
    phrase: " Can I have some more water, please? ",
  },
  {
    meaningId: 54,
    languageCode: "en-US",
    phrase: " What is the best way to get around the city? ",
  },
  { meaningId: 55, languageCode: "en-US", phrase: " Can you speak English? " },
  { meaningId: 56, languageCode: "en-US", phrase: " I don't eat [ingredient]" },
  {
    meaningId: 57,
    languageCode: "en-US",
    phrase: " Where can I find a post office? ",
  },
  {
    meaningId: 58,
    languageCode: "en-US",
    phrase: " What platform does the train/bus leave from? ",
  },
  { meaningId: 59, languageCode: "en-US", phrase: " Can I try it on? " },
  {
    meaningId: 60,
    languageCode: "en-US",
    phrase: " Is there a map of the area? ",
  },
  {
    meaningId: 61,
    languageCode: "en-US",
    phrase: " Can you call a taxi for me? ",
  },
  { meaningId: 62, languageCode: "en-US", phrase: " Is there an ATM nearby? " },
  {
    meaningId: 63,
    languageCode: "en-US",
    phrase: " I'm allergic to [food/allergen]",
  },
  {
    meaningId: 64,
    languageCode: "en-US",
    phrase: " Can you show me on the map? ",
  },
  {
    meaningId: 65,
    languageCode: "en-US",
    phrase: " How long will it take to get there? ",
  },
  {
    meaningId: 66,
    languageCode: "en-US",
    phrase: " Is there parking available? ",
  },
  {
    meaningId: 67,
    languageCode: "en-US",
    phrase: " Can I have a receipt, please? ",
  },
  {
    meaningId: 68,
    languageCode: "en-US",
    phrase: " I don't have a reservation",
  },
  {
    meaningId: 69,
    languageCode: "en-US",
    phrase: " Do you have any vegetarian options? ",
  },
  {
    meaningId: 70,
    languageCode: "en-US",
    phrase: " Can I have the bill, please? ",
  },
  {
    meaningId: 71,
    languageCode: "en-US",
    phrase: " What's the best way to get to the airport? ",
  },
  {
    meaningId: 72,
    languageCode: "en-US",
    phrase: " Is there a nearby gas station? ",
  },
  {
    meaningId: 73,
    languageCode: "en-US",
    phrase: " Can I pay with a credit card? ",
  },
  {
    meaningId: 74,
    languageCode: "en-US",
    phrase: " What is the check-out time? ",
  },
  {
    meaningId: 75,
    languageCode: "en-US",
    phrase: " Can I have a non-smoking room? ",
  },
  {
    meaningId: 76,
    languageCode: "en-US",
    phrase: " What's the exchange rate for [currency]? ",
  },
  {
    meaningId: 77,
    languageCode: "en-US",
    phrase: " Can you recommend a good place for shopping? ",
  },
  {
    meaningId: 78,
    languageCode: "en-US",
    phrase: " I need to go to the embassy",
  },
  {
    meaningId: 79,
    languageCode: "en-US",
    phrase: " Can I have an English menu? ",
  },
  { meaningId: 80, languageCode: "en-US", phrase: " I'm not interested" },
  {
    meaningId: 81,
    languageCode: "en-US",
    phrase: " Where can I catch a bus? ",
  },
  {
    meaningId: 82,
    languageCode: "en-US",
    phrase: " Can you speak slower, please? ",
  },
  {
    meaningId: 83,
    languageCode: "en-US",
    phrase: " What's the best way to get to [tourist attraction]? ",
  },
  { meaningId: 84, languageCode: "en-US", phrase: " I'll have the same" },
  {
    meaningId: 85,
    languageCode: "en-US",
    phrase: " How do I get to the train station? ",
  },
  {
    meaningId: 86,
    languageCode: "en-US",
    phrase: " Is there a public phone nearby? ",
  },
  { meaningId: 87, languageCode: "en-US", phrase: " I'm not feeling well" },
  {
    meaningId: 88,
    languageCode: "en-US",
    phrase: " What's the best way to get to the hotel? ",
  },
  {
    meaningId: 89,
    languageCode: "en-US",
    phrase: " Can you speak louder, please? ",
  },
  { meaningId: 90, languageCode: "en-US", phrase: " I'm looking for [place]" },
  {
    meaningId: 91,
    languageCode: "en-US",
    phrase: " What's the Wi-Fi password? ",
  },
  {
    meaningId: 92,
    languageCode: "en-US",
    phrase: " Can I have a window seat? ",
  },
  { meaningId: 93, languageCode: "en-US", phrase: " This is delicious! " },
  {
    meaningId: 94,
    languageCode: "en-US",
    phrase: " Can you recommend a good hotel? ",
  },
  {
    meaningId: 95,
    languageCode: "en-US",
    phrase: " What's the best way to get to the city center? ",
  },
  {
    meaningId: 96,
    languageCode: "en-US",
    phrase: " I'll have a glass of [drink]",
  },
  { meaningId: 97, languageCode: "en-US", phrase: " Is there an elevator? " },
  {
    meaningId: 98,
    languageCode: "en-US",
    phrase: " Can I have some extra blankets, please? ",
  },
  {
    meaningId: 99,
    languageCode: "en-US",
    phrase: " What's the weather forecast for tomorrow? ",
  },
  { meaningId: 100, languageCode: "en-US", phrase: " Thank you for your help" },
  // フランス語
  { meaningId: 1, languageCode: "fr-FR", phrase: "Bonjour" },
  { meaningId: 2, languageCode: "fr-FR", phrase: "Au revoir" },
  { meaningId: 3, languageCode: "fr-FR", phrase: "Merci" },
  { meaningId: 4, languageCode: "fr-FR", phrase: "S'il vous plaît" },
  { meaningId: 5, languageCode: "fr-FR", phrase: "Excusez-moi" },
  { meaningId: 6, languageCode: "fr-FR", phrase: "Pardon / Désolé(e)" },
  { meaningId: 7, languageCode: "fr-FR", phrase: "Oui" },
  { meaningId: 8, languageCode: "fr-FR", phrase: "Non" },
  { meaningId: 9, languageCode: "fr-FR", phrase: "Comment allez-vous ?" },
  { meaningId: 10, languageCode: "fr-FR", phrase: "Je vais bien, merci" },
  {
    meaningId: 11,
    languageCode: "fr-FR",
    phrase: "Comment vous appelez-vous ?",
  },
  { meaningId: 12, languageCode: "fr-FR", phrase: "Je m'appelle [nom]" },
  { meaningId: 13, languageCode: "fr-FR", phrase: "D'où venez-vous ?" },
  { meaningId: 14, languageCode: "fr-FR", phrase: "Je viens de [pays]" },
  { meaningId: 15, languageCode: "fr-FR", phrase: "Quelle heure est-il ?" },
  { meaningId: 16, languageCode: "fr-FR", phrase: "Pouvez-vous m'aider ?" },
  { meaningId: 17, languageCode: "fr-FR", phrase: "Je ne comprends pas" },
  { meaningId: 18, languageCode: "fr-FR", phrase: "Combien cela coûte-t-il ?" },
  { meaningId: 19, languageCode: "fr-FR", phrase: "Où sont les toilettes ?" },
  { meaningId: 20, languageCode: "fr-FR", phrase: "J'ai besoin d'un médecin" },
  { meaningId: 21, languageCode: "fr-FR", phrase: "Au secours !" },
  { meaningId: 22, languageCode: "fr-FR", phrase: "Je suis perdu(e)" },
  {
    meaningId: 23,
    languageCode: "fr-FR",
    phrase: "Puis-je avoir le menu, s'il vous plaît ?",
  },
  { meaningId: 24, languageCode: "fr-FR", phrase: "Je voudrais [cuisson]" },
  { meaningId: 25, languageCode: "fr-FR", phrase: "Est-ce épicé ?" },
  { meaningId: 26, languageCode: "fr-FR", phrase: "Santé !" },
  {
    meaningId: 27,
    languageCode: "fr-FR",
    phrase: "Où se trouve la gare la plus proche ?",
  },
  {
    meaningId: 28,
    languageCode: "fr-FR",
    phrase: "Combien coûte un billet pour [destination] ?",
  },
  {
    meaningId: 29,
    languageCode: "fr-FR",
    phrase: "Pouvez-vous me prendre en photo ?",
  },
  { meaningId: 30, languageCode: "fr-FR", phrase: "J'adore cet endroit" },
  {
    meaningId: 31,
    languageCode: "fr-FR",
    phrase: "Pouvez-vous recommander un bon restaurant ?",
  },
  {
    meaningId: 32,
    languageCode: "fr-FR",
    phrase: "Quel est votre plat signature ?",
  },
  {
    meaningId: 33,
    languageCode: "fr-FR",
    phrase: "Y a-t-il une pharmacie à proximité ?",
  },
  {
    meaningId: 34,
    languageCode: "fr-FR",
    phrase: "À quelle distance se trouve [emplacement] ?",
  },
  {
    meaningId: 35,
    languageCode: "fr-FR",
    phrase: "Pouvez-vous parler plus lentement ?",
  },
  {
    meaningId: 36,
    languageCode: "fr-FR",
    phrase: "Où puis-je acheter des souvenirs ?",
  },
  {
    meaningId: 37,
    languageCode: "fr-FR",
    phrase: "Est-ce que je peux avoir une réduction ?",
  },
  {
    meaningId: 38,
    languageCode: "fr-FR",
    phrase: "Y a-t-il du Wi-Fi gratuit ici ?",
  },
  {
    meaningId: 39,
    languageCode: "fr-FR",
    phrase: "Quel temps fait-il aujourd'hui ?",
  },
  {
    meaningId: 40,
    languageCode: "fr-FR",
    phrase: "Pouvez-vous recommander des attractions locales ?",
  },
  { meaningId: 41, languageCode: "fr-FR", phrase: "J'ai besoin d'un taxi" },
  {
    meaningId: 42,
    languageCode: "fr-FR",
    phrase: "Combien pour aller à l'aéroport ?",
  },
  { meaningId: 43, languageCode: "fr-FR", phrase: "J'ai une réservation" },
  {
    meaningId: 44,
    languageCode: "fr-FR",
    phrase: "Le petit-déjeuner est-il inclus ?",
  },
  {
    meaningId: 45,
    languageCode: "fr-FR",
    phrase: "Puis-je avoir un réveil à [temps] ?",
  },
  {
    meaningId: 46,
    languageCode: "fr-FR",
    phrase: "Y a-t-il un coffre-fort dans la chambre ?",
  },
  {
    meaningId: 47,
    languageCode: "fr-FR",
    phrase: "À quelle heure ouvre/ferme [attirance] ?",
  },
  {
    meaningId: 48,
    languageCode: "fr-FR",
    phrase: "Pouvez-vous recommander un bon endroit pour se promener ?",
  },
  {
    meaningId: 49,
    languageCode: "fr-FR",
    phrase: "J'aimerais aller à [lieu]",
  },
  { meaningId: 50, languageCode: "fr-FR", phrase: "Est-il sûr de nager ici ?" },
  {
    meaningId: 51,
    languageCode: "fr-FR",
    phrase: "Comment puis-je aller à [destination] ?",
  },
  {
    meaningId: 52,
    languageCode: "fr-FR",
    phrase: "Pouvez-vous l'écrire pour moi ?",
  },
  {
    meaningId: 53,
    languageCode: "fr-FR",
    phrase: "Puis-je avoir encore un peu d'eau, s'il vous plaît ?",
  },
  {
    meaningId: 54,
    languageCode: "fr-FR",
    phrase: "Quel est le meilleur moyen de se déplacer dans la ville ?",
  },
  { meaningId: 55, languageCode: "fr-FR", phrase: "Parlez-vous anglais ?" },
  {
    meaningId: 56,
    languageCode: "fr-FR",
    phrase: "Je ne mange pas [ingrédient]",
  },
  {
    meaningId: 57,
    languageCode: "fr-FR",
    phrase: "Où puis-je trouver un bureau de poste ?",
  },
  {
    meaningId: 58,
    languageCode: "fr-FR",
    phrase: "De quel quai part le train/bus ?",
  },
  { meaningId: 59, languageCode: "fr-FR", phrase: "Puis-je l'essayer ?" },
  {
    meaningId: 60,
    languageCode: "fr-FR",
    phrase: "Y a-t-il une carte de la région ?",
  },
  {
    meaningId: 61,
    languageCode: "fr-FR",
    phrase: "Pouvez-vous appeler un taxi pour moi ?",
  },
  {
    meaningId: 62,
    languageCode: "fr-FR",
    phrase: "Y a-t-il un distributeur de billets à proximité ?",
  },
  {
    meaningId: 63,
    languageCode: "fr-FR",
    phrase: "Je suis allergique aux [aliment/allergène]",
  },
  {
    meaningId: 64,
    languageCode: "fr-FR",
    phrase: "Pouvez-vous me montrer sur la carte ?",
  },
  {
    meaningId: 65,
    languageCode: "fr-FR",
    phrase: "Combien de temps cela prendra-t-il pour y arriver ?",
  },
  {
    meaningId: 66,
    languageCode: "fr-FR",
    phrase: "Y a-t-il un parking disponible ?",
  },
  {
    meaningId: 67,
    languageCode: "fr-FR",
    phrase: "Puis-je avoir un reçu, s'il vous plaît ?",
  },
  {
    meaningId: 68,
    languageCode: "fr-FR",
    phrase: "Je n'ai pas de réservation",
  },
  {
    meaningId: 69,
    languageCode: "fr-FR",
    phrase: "Avez-vous des options végétariennes ?",
  },
  {
    meaningId: 70,
    languageCode: "fr-FR",
    phrase: "L'addition, s'il vous plaît ?",
  },
  {
    meaningId: 71,
    languageCode: "fr-FR",
    phrase: "Quel est le meilleur moyen d'aller à l'aéroport ?",
  },
  {
    meaningId: 72,
    languageCode: "fr-FR",
    phrase: "Y a-t-il une station-service à proximité ?",
  },
  {
    meaningId: 73,
    languageCode: "fr-FR",
    phrase: "Puis-je payer par carte de crédit ?",
  },
  {
    meaningId: 74,
    languageCode: "fr-FR",
    phrase: "À quelle heure est le check-out ?",
  },
  {
    meaningId: 75,
    languageCode: "fr-FR",
    phrase: "Puis-je avoir une chambre non-fumeur ?",
  },
  {
    meaningId: 76,
    languageCode: "fr-FR",
    phrase: "Quel est le taux de change pour [monnaie] ?",
  },
  {
    meaningId: 77,
    languageCode: "fr-FR",
    phrase: "Pouvez-vous recommander un bon endroit pour faire des achats ?",
  },
  {
    meaningId: 78,
    languageCode: "fr-FR",
    phrase: "J'ai besoin d'aller à l'ambassade",
  },
  {
    meaningId: 79,
    languageCode: "fr-FR",
    phrase: "Puis-je avoir un menu en anglais ?",
  },
  {
    meaningId: 80,
    languageCode: "fr-FR",
    phrase: "Je ne suis pas intéressé(e)",
  },
  {
    meaningId: 81,
    languageCode: "fr-FR",
    phrase: "Où puis-je prendre un bus ?",
  },
  {
    meaningId: 82,
    languageCode: "fr-FR",
    phrase: "Pouvez-vous parler plus lentement, s'il vous plaît ?",
  },
  {
    meaningId: 83,
    languageCode: "fr-FR",
    phrase: "Quel est le meilleur moyen d'aller à [attraction touristique] ?",
  },
  { meaningId: 84, languageCode: "fr-FR", phrase: "Je prendrai la même chose" },
  {
    meaningId: 85,
    languageCode: "fr-FR",
    phrase: "Comment vais-je à la gare ?",
  },
  {
    meaningId: 86,
    languageCode: "fr-FR",
    phrase: "Y a-t-il un téléphone public à proximité ?",
  },
  { meaningId: 87, languageCode: "fr-FR", phrase: "Je ne me sens pas bien" },
  {
    meaningId: 88,
    languageCode: "fr-FR",
    phrase: "Quel est le meilleur moyen d'aller à l'hôtel ?",
  },
  {
    meaningId: 89,
    languageCode: "fr-FR",
    phrase: "Pouvez-vous parler plus fort, s'il vous plaît ?",
  },
  { meaningId: 90, languageCode: "fr-FR", phrase: "Je cherche [lieu]" },
  {
    meaningId: 91,
    languageCode: "fr-FR",
    phrase: "Quel est le mot de passe Wi-Fi ?",
  },
  {
    meaningId: 92,
    languageCode: "fr-FR",
    phrase: "Puis-je avoir une place près de la fenêtre ?",
  },
  { meaningId: 93, languageCode: "fr-FR", phrase: "C'est délicieux !" },
  {
    meaningId: 94,
    languageCode: "fr-FR",
    phrase: "Pouvez-vous recommander un bon hôtel ?",
  },
  {
    meaningId: 95,
    languageCode: "fr-FR",
    phrase: "Quel est le meilleur moyen d'aller au centre-ville ?",
  },
  {
    meaningId: 96,
    languageCode: "fr-FR",
    phrase: "Je prendrai un verre de [boire]",
  },
  { meaningId: 97, languageCode: "fr-FR", phrase: "Y a-t-il un ascenseur ?" },
  {
    meaningId: 98,
    languageCode: "fr-FR",
    phrase: "Puis-je avoir des couvertures supplémentaires, s'il vous plaît ?",
  },
  {
    meaningId: 99,
    languageCode: "fr-FR",
    phrase: "Quel est le bulletin météo pour demain ?",
  },
  { meaningId: 100, languageCode: "fr-FR", phrase: "Merci pour votre aide" },
  //　ドイツ語
  { meaningId: 1, languageCode: "de-DE", phrase: "Hallo" },
  { meaningId: 2, languageCode: "de-DE", phrase: "Auf Wiedersehen" },
  { meaningId: 3, languageCode: "de-DE", phrase: "Danke" },
  { meaningId: 4, languageCode: "de-DE", phrase: "Bitte" },
  { meaningId: 5, languageCode: "de-DE", phrase: "Entschuldigung" },
  { meaningId: 6, languageCode: "de-DE", phrase: "Es tut mir leid" },
  { meaningId: 7, languageCode: "de-DE", phrase: "Ja" },
  { meaningId: 8, languageCode: "de-DE", phrase: "Nein" },
  { meaningId: 9, languageCode: "de-DE", phrase: "Wie geht es Ihnen?" },
  { meaningId: 10, languageCode: "de-DE", phrase: "Mir geht es gut, danke" },
  { meaningId: 11, languageCode: "de-DE", phrase: "Wie heißen Sie?" },
  { meaningId: 12, languageCode: "de-DE", phrase: "Ich heiße [name]" },
  { meaningId: 13, languageCode: "de-DE", phrase: "Woher kommen Sie?" },
  { meaningId: 14, languageCode: "de-DE", phrase: "Ich komme aus [Land]" },
  { meaningId: 15, languageCode: "de-DE", phrase: "Wie spät ist es?" },
  { meaningId: 16, languageCode: "de-DE", phrase: "Können Sie mir helfen?" },
  { meaningId: 17, languageCode: "de-DE", phrase: "Ich verstehe nicht" },
  { meaningId: 18, languageCode: "de-DE", phrase: "Wie viel kostet das?" },
  { meaningId: 19, languageCode: "de-DE", phrase: "Wo ist die Toilette?" },
  { meaningId: 20, languageCode: "de-DE", phrase: "Ich brauche einen Arzt" },
  { meaningId: 21, languageCode: "de-DE", phrase: "Hilfe!" },
  { meaningId: 22, languageCode: "de-DE", phrase: "Ich habe mich verirrt" },
  {
    meaningId: 23,
    languageCode: "de-DE",
    phrase: "Kann ich bitte die Speisekarte haben?",
  },
  { meaningId: 24, languageCode: "de-DE", phrase: "Ich hätte gerne [Kochen]" },
  { meaningId: 25, languageCode: "de-DE", phrase: "Ist das scharf?" },
  { meaningId: 26, languageCode: "de-DE", phrase: "Prost!" },
  {
    meaningId: 27,
    languageCode: "de-DE",
    phrase: "Wo ist der nächste Bahnhof?",
  },
  {
    meaningId: 28,
    languageCode: "de-DE",
    phrase: "Wie viel kostet ein Ticket nach [Ziel]?",
  },
  {
    meaningId: 29,
    languageCode: "de-DE",
    phrase: "Können Sie ein Foto von mir machen?",
  },
  { meaningId: 30, languageCode: "de-DE", phrase: "Ich liebe diesen Ort" },
  {
    meaningId: 31,
    languageCode: "de-DE",
    phrase: "Können Sie ein gutes Restaurant empfehlen?",
  },
  {
    meaningId: 32,
    languageCode: "de-DE",
    phrase: "Was ist Ihr Spezialgericht?",
  },
  {
    meaningId: 33,
    languageCode: "de-DE",
    phrase: "Gibt es eine Apotheke in der Nähe?",
  },
  {
    meaningId: 34,
    languageCode: "de-DE",
    phrase: "Wie weit ist [Standort] entfernt?",
  },
  {
    meaningId: 35,
    languageCode: "de-DE",
    phrase: "Können Sie langsamer sprechen?",
  },
  {
    meaningId: 36,
    languageCode: "de-DE",
    phrase: "Wo kann ich Souvenirs kaufen?",
  },
  { meaningId: 37, languageCode: "de-DE", phrase: "Bekomme ich einen Rabatt?" },
  {
    meaningId: 38,
    languageCode: "de-DE",
    phrase: "Gibt es hier kostenloses WLAN?",
  },
  { meaningId: 39, languageCode: "de-DE", phrase: "Wie ist das Wetter heute?" },
  {
    meaningId: 40,
    languageCode: "de-DE",
    phrase: "Können Sie lokale Sehenswürdigkeiten empfehlen?",
  },
  { meaningId: 41, languageCode: "de-DE", phrase: "Ich brauche ein Taxi" },
  {
    meaningId: 42,
    languageCode: "de-DE",
    phrase: "Wie viel kostet es zum Flughafen?",
  },
  {
    meaningId: 43,
    languageCode: "de-DE",
    phrase: "Ich habe eine Reservierung",
  },
  {
    meaningId: 44,
    languageCode: "de-DE",
    phrase: "Ist das Frühstück inklusive?",
  },
  {
    meaningId: 45,
    languageCode: "de-DE",
    phrase: "Können Sie mich um [Uhrzeit] wecken?",
  },
  {
    meaningId: 46,
    languageCode: "de-DE",
    phrase: "Gibt es einen Safe im Zimmer?",
  },
  {
    meaningId: 47,
    languageCode: "de-DE",
    phrase: "Wann öffnet/schließt [Attraktion]?",
  },
  {
    meaningId: 48,
    languageCode: "de-DE",
    phrase: "Können Sie einen schönen Ort zum Spazierengehen empfehlen?",
  },
  {
    meaningId: 49,
    languageCode: "de-DE",
    phrase: "Ich möchte gerne nach [Ort]",
  },
  {
    meaningId: 50,
    languageCode: "de-DE",
    phrase: "Ist es sicher, hier zu schwimmen?",
  },
  {
    meaningId: 51,
    languageCode: "de-DE",
    phrase: "Wie komme ich nach [Ziel]?",
  },
  {
    meaningId: 52,
    languageCode: "de-DE",
    phrase: "Können Sie das für mich aufschreiben?",
  },
  {
    meaningId: 53,
    languageCode: "de-DE",
    phrase: "Kann ich noch etwas Wasser haben, bitte?",
  },
  {
    meaningId: 54,
    languageCode: "de-DE",
    phrase: "Was ist die beste Art, sich in der Stadt fortzubewegen?",
  },
  { meaningId: 55, languageCode: "de-DE", phrase: "Sprechen Sie Englisch?" },
  {
    meaningId: 56,
    languageCode: "de-DE",
    phrase: "Ich esse kein [ingredient]",
  },
  { meaningId: 57, languageCode: "de-DE", phrase: "Wo finde ich ein Postamt?" },
  {
    meaningId: 58,
    languageCode: "de-DE",
    phrase: "Von welchem Gleis fährt der Zug/Bus ab?",
  },
  { meaningId: 59, languageCode: "de-DE", phrase: "Kann ich es anprobieren?" },
  {
    meaningId: 60,
    languageCode: "de-DE",
    phrase: "Gibt es eine Karte der Gegend?",
  },
  {
    meaningId: 61,
    languageCode: "de-DE",
    phrase: "Können Sie ein Taxi für mich rufen?",
  },
  {
    meaningId: 62,
    languageCode: "de-DE",
    phrase: "Gibt es einen Geldautomaten in der Nähe?",
  },
  {
    meaningId: 63,
    languageCode: "de-DE",
    phrase: "Ich bin allergisch gegen [Lebensmittel/Allergen]",
  },
  {
    meaningId: 64,
    languageCode: "de-DE",
    phrase: "Können Sie es mir auf der Karte zeigen?",
  },
  {
    meaningId: 65,
    languageCode: "de-DE",
    phrase: "Wie lange dauert es, um dorthin zu gelangen?",
  },
  { meaningId: 66, languageCode: "de-DE", phrase: "Gibt es Parkplätze?" },
  {
    meaningId: 67,
    languageCode: "de-DE",
    phrase: "Kann ich bitte eine Quittung haben?",
  },
  {
    meaningId: 68,
    languageCode: "de-DE",
    phrase: "Ich habe keine Reservierung",
  },
  {
    meaningId: 69,
    languageCode: "de-DE",
    phrase: "Haben Sie vegetarische Optionen?",
  },
  {
    meaningId: 70,
    languageCode: "de-DE",
    phrase: "Kann ich bitte die Rechnung haben?",
  },
  {
    meaningId: 71,
    languageCode: "de-DE",
    phrase: "Wie komme ich am besten zum Flughafen?",
  },
  {
    meaningId: 72,
    languageCode: "de-DE",
    phrase: "Gibt es eine Tankstelle in der Nähe?",
  },
  {
    meaningId: 73,
    languageCode: "de-DE",
    phrase: "Kann ich mit Kreditkarte bezahlen?",
  },
  {
    meaningId: 74,
    languageCode: "de-DE",
    phrase: "Wann ist die Check-out-Zeit?",
  },
  {
    meaningId: 75,
    languageCode: "de-DE",
    phrase: "Kann ich ein Nichtraucherzimmer haben?",
  },
  {
    meaningId: 76,
    languageCode: "de-DE",
    phrase: "Wie ist der Wechselkurs für [Währung]?",
  },
  {
    meaningId: 77,
    languageCode: "de-DE",
    phrase: "Können Sie einen guten Ort zum Einkaufen empfehlen?",
  },
  { meaningId: 78, languageCode: "de-DE", phrase: "Ich muss zur Botschaft" },
  {
    meaningId: 79,
    languageCode: "de-DE",
    phrase: "Kann ich eine englische Speisekarte haben?",
  },
  {
    meaningId: 80,
    languageCode: "de-DE",
    phrase: "Ich bin nicht interessiert",
  },
  {
    meaningId: 81,
    languageCode: "de-DE",
    phrase: "Wo kann ich einen Bus nehmen?",
  },
  {
    meaningId: 82,
    languageCode: "de-DE",
    phrase: "Können Sie bitte langsamer sprechen?",
  },
  {
    meaningId: 83,
    languageCode: "de-DE",
    phrase: "Wie kommt man am besten zu [Touristenattraktion]?",
  },
  { meaningId: 84, languageCode: "de-DE", phrase: "Ich nehme das Gleiche" },
  {
    meaningId: 85,
    languageCode: "de-DE",
    phrase: "Wie komme ich zum Bahnhof?",
  },
  {
    meaningId: 86,
    languageCode: "de-DE",
    phrase: "Gibt es in der Nähe einen öffentlichen Telefon?",
  },
  { meaningId: 87, languageCode: "de-DE", phrase: "Mir ist nicht gut" },
  {
    meaningId: 88,
    languageCode: "de-DE",
    phrase: "Wie komme ich am besten zum Hotel?",
  },
  {
    meaningId: 89,
    languageCode: "de-DE",
    phrase: "Können Sie bitte lauter sprechen?",
  },
  { meaningId: 90, languageCode: "de-DE", phrase: "Ich suche [Ort]" },
  {
    meaningId: 91,
    languageCode: "de-DE",
    phrase: "Was ist das WLAN-Passwort?",
  },
  {
    meaningId: 92,
    languageCode: "de-DE",
    phrase: "Kann ich einen Platz am Fenster haben?",
  },
  { meaningId: 93, languageCode: "de-DE", phrase: "Das ist köstlich!" },
  {
    meaningId: 94,
    languageCode: "de-DE",
    phrase: "Können Sie ein gutes Hotel empfehlen?",
  },
  {
    meaningId: 95,
    languageCode: "de-DE",
    phrase: "Wie kommt man am besten ins Stadtzentrum?",
  },
  {
    meaningId: 96,
    languageCode: "de-DE",
    phrase: "Ich nehme ein Glas [trinken]",
  },
  { meaningId: 97, languageCode: "de-DE", phrase: "Gibt es einen Aufzug?" },
  {
    meaningId: 98,
    languageCode: "de-DE",
    phrase: "Kann ich bitte zusätzliche Decken haben?",
  },
  {
    meaningId: 99,
    languageCode: "de-DE",
    phrase: "Wie ist die Wettervorhersage für morgen?",
  },
  { meaningId: 100, languageCode: "de-DE", phrase: "Danke für Ihre Hilfe" },
  // 中国語
  { meaningId: 1, languageCode: "zh-CN", phrase: "你好。" },
  { meaningId: 2, languageCode: "zh-CN", phrase: "再见。" },
  { meaningId: 3, languageCode: "zh-CN", phrase: "谢谢。" },
  { meaningId: 4, languageCode: "zh-CN", phrase: "请。" },
  { meaningId: 5, languageCode: "zh-CN", phrase: "对不起。" },
  { meaningId: 6, languageCode: "zh-CN", phrase: "对不起。" },
  { meaningId: 7, languageCode: "zh-CN", phrase: "是的。" },
  { meaningId: 8, languageCode: "zh-CN", phrase: "不。" },
  { meaningId: 9, languageCode: "zh-CN", phrase: "你好吗？" },
  { meaningId: 10, languageCode: "zh-CN", phrase: "我很好，谢谢。" },
  { meaningId: 11, languageCode: "zh-CN", phrase: "请问你叫什么名字？" },
  { meaningId: 12, languageCode: "zh-CN", phrase: "我的名字是［名字］。" },
  { meaningId: 13, languageCode: "zh-CN", phrase: "你来自哪里？" },
  { meaningId: 14, languageCode: "zh-CN", phrase: "我来自［国家］。" },
  { meaningId: 15, languageCode: "zh-CN", phrase: "现在几点了？" },
  { meaningId: 16, languageCode: "zh-CN", phrase: "可以帮忙吗？" },
  { meaningId: 17, languageCode: "zh-CN", phrase: "我不知道。" },
  { meaningId: 18, languageCode: "zh-CN", phrase: "这个多少钱？" },
  { meaningId: 19, languageCode: "zh-CN", phrase: "洗手间在哪里？" },
  { meaningId: 20, languageCode: "zh-CN", phrase: "我需要医生。" },
  { meaningId: 21, languageCode: "zh-CN", phrase: "救命！" },
  { meaningId: 22, languageCode: "zh-CN", phrase: "我迷路了。" },
  { meaningId: 23, languageCode: "zh-CN", phrase: "请给我菜单。" },
  { meaningId: 24, languageCode: "zh-CN", phrase: "我想点［菜名］。" },
  { meaningId: 25, languageCode: "zh-CN", phrase: "这个很辣吗？" },
  { meaningId: 26, languageCode: "zh-CN", phrase: "干杯！" },
  { meaningId: 27, languageCode: "zh-CN", phrase: "最近的车站在哪里？" },
  { meaningId: 28, languageCode: "zh-CN", phrase: "去［目的地］的票多少钱？" },
  { meaningId: 29, languageCode: "zh-CN", phrase: "可以给我拍照吗？" },
  { meaningId: 30, languageCode: "zh-CN", phrase: "我喜欢这里。" },
  { meaningId: 31, languageCode: "zh-CN", phrase: "请告诉我推荐的餐馆。" },
  { meaningId: 32, languageCode: "zh-CN", phrase: "你们的特色菜是什么？" },
  { meaningId: 33, languageCode: "zh-CN", phrase: "附近有药店吗？" },
  { meaningId: 34, languageCode: "zh-CN", phrase: "到［地点］有多远？" },
  { meaningId: 35, languageCode: "zh-CN", phrase: "可以说得再慢一点吗？" },
  { meaningId: 36, languageCode: "zh-CN", phrase: "在哪里可以买纪念品？" },
  { meaningId: 37, languageCode: "zh-CN", phrase: "可以给折扣吗？" },
  { meaningId: 38, languageCode: "zh-CN", phrase: "这里有免费的Wi-Fi吗？" },
  { meaningId: 39, languageCode: "zh-CN", phrase: "今天天气怎么样？" },
  { meaningId: 40, languageCode: "zh-CN", phrase: "请告诉我本地的旅游景点。" },
  { meaningId: 41, languageCode: "zh-CN", phrase: "请叫出租车。" },
  { meaningId: 42, languageCode: "zh-CN", phrase: "去机场多少钱？" },
  { meaningId: 43, languageCode: "zh-CN", phrase: "我已经预订了。" },
  { meaningId: 44, languageCode: "zh-CN", phrase: "包括早餐吗？" },
  { meaningId: 45, languageCode: "zh-CN", phrase: "[时间]给我打早晨电话。" },
  { meaningId: 46, languageCode: "zh-CN", phrase: "房间有保险箱吗？" },
  { meaningId: 47, languageCode: "zh-CN", phrase: "[观光地点]几点开门/关门？" },
  { meaningId: 48, languageCode: "zh-CN", phrase: "请告诉我推荐的散步地点。" },
  { meaningId: 49, languageCode: "zh-CN", phrase: "我想去［地点］。" },
  { meaningId: 50, languageCode: "zh-CN", phrase: "这里可以游泳吗？" },
  { meaningId: 51, languageCode: "zh-CN", phrase: "怎样去［目的地］？" },
  { meaningId: 52, languageCode: "zh-CN", phrase: "可以帮我记下来吗？" },
  { meaningId: 53, languageCode: "zh-CN", phrase: "可以再给点水吗？" },
  {
    meaningId: 54,
    languageCode: "zh-CN",
    phrase: "去城市里最方便的方式是什么？",
  },
  { meaningId: 55, languageCode: "zh-CN", phrase: "你会说英语吗？" },
  { meaningId: 56, languageCode: "zh-CN", phrase: "[食材]不能吃。" },
  { meaningId: 57, languageCode: "zh-CN", phrase: "邮局在哪里？" },
  { meaningId: 58, languageCode: "zh-CN", phrase: "火车/公交车从几号线出发？" },
  { meaningId: 59, languageCode: "zh-CN", phrase: "可以试穿吗？" },
  { meaningId: 60, languageCode: "zh-CN", phrase: "有地图吗？" },
  { meaningId: 61, languageCode: "zh-CN", phrase: "请叫出租车。" },
  { meaningId: 62, languageCode: "zh-CN", phrase: "附近有ATM吗？" },
  { meaningId: 63, languageCode: "zh-CN", phrase: "[食物/过敏原]对我过敏。" },
  { meaningId: 64, languageCode: "zh-CN", phrase: "可以在地图上指示吗？" },
  { meaningId: 65, languageCode: "zh-CN", phrase: "去那里要多长时间？" },
  { meaningId: 66, languageCode: "zh-CN", phrase: "有停车场吗？" },
  { meaningId: 67, languageCode: "zh-CN", phrase: "可以开个收据给我吗？" },
  { meaningId: 68, languageCode: "zh-CN", phrase: "我没有预定。" },
  { meaningId: 69, languageCode: "zh-CN", phrase: "有素食选项吗？" },
  { meaningId: 70, languageCode: "zh-CN", phrase: "请结账。" },
  {
    meaningId: 71,
    languageCode: "zh-CN",
    phrase: "去机场最方便的方式是什么？",
  },
  { meaningId: 72, languageCode: "zh-CN", phrase: "附近有加油站吗？" },
  { meaningId: 73, languageCode: "zh-CN", phrase: "可以用信用卡支付吗？" },
  { meaningId: 74, languageCode: "zh-CN", phrase: "退房的时间是几点？" },
  { meaningId: 75, languageCode: "zh-CN", phrase: "可以给无烟房吗？" },
  { meaningId: 76, languageCode: "zh-CN", phrase: "[货币]的汇率是多少？" },
  { meaningId: 77, languageCode: "zh-CN", phrase: "请告诉我推荐的购物地点。" },
  { meaningId: 78, languageCode: "zh-CN", phrase: "我需要去大使馆。" },
  { meaningId: 79, languageCode: "zh-CN", phrase: "有英语菜单吗？" },
  { meaningId: 80, languageCode: "zh-CN", phrase: "我不感兴趣。" },
  { meaningId: 81, languageCode: "zh-CN", phrase: "公交车在哪里可以坐？" },
  { meaningId: 82, languageCode: "zh-CN", phrase: "请慢点说。" },
  {
    meaningId: 83,
    languageCode: "zh-CN",
    phrase: "去［观光地点］最方便的方式是什么？",
  },
  { meaningId: 84, languageCode: "zh-CN", phrase: "我要再点一样。" },
  { meaningId: 85, languageCode: "zh-CN", phrase: "怎么去车站？" },
  { meaningId: 86, languageCode: "zh-CN", phrase: "附近有公用电话吗？" },
  { meaningId: 87, languageCode: "zh-CN", phrase: "我不舒服。" },
  {
    meaningId: 88,
    languageCode: "zh-CN",
    phrase: "去酒店最方便的方式是什么？",
  },
  { meaningId: 89, languageCode: "zh-CN", phrase: "可以再大声一点吗？" },
  { meaningId: 90, languageCode: "zh-CN", phrase: "正在寻找［地点］。" },
  { meaningId: 91, languageCode: "zh-CN", phrase: "Wi-Fi密码是什么？" },
  { meaningId: 92, languageCode: "zh-CN", phrase: "可以坐在靠窗的座位吗？" },
  { meaningId: 93, languageCode: "zh-CN", phrase: "这个好吃！" },
  { meaningId: 94, languageCode: "zh-CN", phrase: "请推荐一家酒店。" },
  {
    meaningId: 95,
    languageCode: "zh-CN",
    phrase: "去市中心的最佳方式是什么？",
  },
  { meaningId: 96, languageCode: "zh-CN", phrase: "请给我一杯［饮料］。" },
  { meaningId: 97, languageCode: "zh-CN", phrase: "有电梯吗？" },
  { meaningId: 98, languageCode: "zh-CN", phrase: "可以再给我一条毛巾吗？" },
  { meaningId: 99, languageCode: "zh-CN", phrase: "明天的天气预报怎么样？" },
  { meaningId: 100, languageCode: "zh-CN", phrase: "谢谢你的帮助。" },
  /*
  //韓国語
  { meaningId: 1, languageCode: "ko-KR", phrase: "안녕하세요." },
  { meaningId: 2, languageCode: "ko-KR", phrase: "안녕히 가세요." },
  { meaningId: 3, languageCode: "ko-KR", phrase: "감사합니다." },
  { meaningId: 4, languageCode: "ko-KR", phrase: "부탁합니다." },
  { meaningId: 5, languageCode: "ko-KR", phrase: "미안합니다." },
  { meaningId: 6, languageCode: "ko-KR", phrase: "사과합니다." },
  { meaningId: 7, languageCode: "ko-KR", phrase: "네." },
  { meaningId: 8, languageCode: "ko-KR", phrase: "아니요." },
  { meaningId: 9, languageCode: "ko-KR", phrase: "안녕하세요?" },
  { meaningId: 10, languageCode: "ko-KR", phrase: "네, 잘 지내요. 감사합니다." },
  { meaningId: 11, languageCode: "ko-KR", phrase: "이름이 뭐에요?" },
  { meaningId: 12, languageCode: "ko-KR", phrase: "제 이름은 [이름]입니다." },
  { meaningId: 13, languageCode: "ko-KR", phrase: "출신은 어디에요?" },
  { meaningId: 14, languageCode: "ko-KR", phrase: "저는 [국가명] 출신입니다." },
  { meaningId: 15, languageCode: "ko-KR", phrase: "지금 몇 시에요?" },
  { meaningId: 16, languageCode: "ko-KR", phrase: "도와주실 수 있을까요?" },
  { meaningId: 17, languageCode: "ko-KR", phrase: "잘 모르겠어요." },
  { meaningId: 18, languageCode: "ko-KR", phrase: "이거 얼마에요?" },
  { meaningId: 19, languageCode: "ko-KR", phrase: "화장실은 어디에요?" },
  { meaningId: 20, languageCode: "ko-KR", phrase: "의사가 필요해요." },
  { meaningId: 21, languageCode: "ko-KR", phrase: "도와주세요!" },
  { meaningId: 22, languageCode: "ko-KR", phrase: "길을 잃었어요." },
  { meaningId: 23, languageCode: "ko-KR", phrase: "메뉴 주세요." },
  { meaningId: 24, languageCode: "ko-KR", phrase: "[요리] 주문하고 싶어요." },
  { meaningId: 25, languageCode: "ko-KR", phrase: "이거 맵니까?" },
  { meaningId: 26, languageCode: "ko-KR", phrase: "건배!" },
  { meaningId: 27, languageCode: "ko-KR", phrase: "가장 가까운 역은 어디에요?" },
  { meaningId: 28, languageCode: "ko-KR", phrase: "[목적지] 행 표가 얼마에요?" },
  { meaningId: 29, languageCode: "ko-KR", phrase: "사진을 찍어 주시겠어요?" },
  { meaningId: 30, languageCode: "ko-KR", phrase: "여기를 정말 좋아해요." },
  {
    meaningId: 31,
    languageCode: "ko-KR",
    phrase: "추천해주시는 레스토랑이 어디에요?",
  },
  { meaningId: 32, languageCode: "ko-KR", phrase: "저자랑 음식이 뭐에요?" },
  { meaningId: 33, languageCode: "ko-KR", phrase: "근처에 약국이 있나요?" },
  {
    meaningId: 34,
    languageCode: "ko-KR",
    phrase: "[장소]은(는) 얼마나 떨어져 있어요?",
  },
  { meaningId: 35, languageCode: "ko-KR", phrase: "더 천천히 말씀해 주실래요?" },
  { meaningId: 36, languageCode: "ko-KR", phrase: "기념품은 어디서 사나요?" },
  { meaningId: 37, languageCode: "ko-KR", phrase: "할인해 주시겠어요?" },
  {
    meaningId: 38,
    languageCode: "ko-KR",
    phrase: "여기서 무료 Wi-Fi를 사용할 수 있나요?",
  },
  { meaningId: 39, languageCode: "ko-KR", phrase: "오늘 날씨는 어떤가요?" },
  { meaningId: 40, languageCode: "ko-KR", phrase: "현지 관광명소를 알려주세요." },
  { meaningId: 41, languageCode: "ko-KR", phrase: "택시를 불러주세요." },
  { meaningId: 42, languageCode: "ko-KR", phrase: "공항까지 얼마에요?" },
  { meaningId: 43, languageCode: "ko-KR", phrase: "예약되어 있어요." },
  { meaningId: 44, languageCode: "ko-KR", phrase: "조식이 포함되어 있나요?" },
  { meaningId: 45, languageCode: "ko-KR", phrase: "[시간]에 모닝콜 해주세요." },
  { meaningId: 46, languageCode: "ko-KR", phrase: "방에 금고가 있나요?" },
  {
    meaningId: 47,
    languageCode: "ko-KR",
    phrase: "[관광지]은(는) 몇 시에 문을 닫나요?",
  },
  {
    meaningId: 48,
    languageCode: "ko-KR",
    phrase: "추천하는 산책 장소가 어디에요?",
  },
  { meaningId: 49, languageCode: "ko-KR", phrase: "[장소]에 가고 싶어요." },
  { meaningId: 50, languageCode: "ko-KR", phrase: "여기에서 수영해도 괜찮아요?" },
  {
    meaningId: 51,
    languageCode: "ko-KR",
    phrase: "[목적지]로 가려면 어떻게 가야 해요?",
  },
  { meaningId: 52, languageCode: "ko-KR", phrase: "메모해 주시겠어요?" },
  { meaningId: 53, languageCode: "ko-KR", phrase: "물 좀 더 주시겠어요?" },
  {
    meaningId: 54,
    languageCode: "ko-KR",
    phrase: "도시 이동하는데 최적의 방법은 뭐에요?",
  },
  { meaningId: 55, languageCode: "ko-KR", phrase: "영어 할 수 있어요?" },
  {
    meaningId: 56,
    languageCode: "ko-KR",
    phrase: "[식재료]는(은) 먹을 수 없어요.",
  },
  { meaningId: 57, languageCode: "ko-KR", phrase: "우체국은 어디에 있나요?" },
  {
    meaningId: 58,
    languageCode: "ko-KR",
    phrase: "전철/버스는 몇 번 환승하면 가나요?",
  },
  { meaningId: 59, languageCode: "ko-KR", phrase: "옷 입어봐도 될까요?" },
  { meaningId: 60, languageCode: "ko-KR", phrase: "지도 있나요?" },
  { meaningId: 61, languageCode: "ko-KR", phrase: "택시를 불러 주시겠어요?" },
  { meaningId: 62, languageCode: "ko-KR", phrase: "근처에 ATM이 있나요?" },
  {
    meaningId: 63,
    languageCode: "ko-KR",
    phrase: "[음식/알레르기] 알레르기가 있어요.",
  },
  { meaningId: 64, languageCode: "ko-KR", phrase: "지도로 보여주시겠어요?" },
  { meaningId: 65, languageCode: "ko-KR", phrase: "거기까지 얼마나 걸려요?" },
  { meaningId: 66, languageCode: "ko-KR", phrase: "주차장이 있나요?" },
  { meaningId: 67, languageCode: "ko-KR", phrase: "영수증 받을 수 있을까요?" },
  { meaningId: 68, languageCode: "ko-KR", phrase: "예약하지 않았어요." },
  { meaningId: 69, languageCode: "ko-KR", phrase: "채식주의자 옵션은 있나요?" },
  { meaningId: 70, languageCode: "ko-KR", phrase: "계산서 주세요." },
  {
    meaningId: 71,
    languageCode: "ko-KR",
    phrase: "공항까지 최적의 방법은 뭐에요?",
  },
  { meaningId: 72, languageCode: "ko-KR", phrase: "근처에 주유소가 있나요?" },
  {
    meaningId: 73,
    languageCode: "ko-KR",
    phrase: "신용카드로 결제할 수 있나요?",
  },
  { meaningId: 74, languageCode: "ko-KR", phrase: "체크아웃 시간은 몇 시에요?" },
  { meaningId: 75, languageCode: "ko-KR", phrase: "금연실 부탁드려도 될까요?" },
  { meaningId: 76, languageCode: "ko-KR", phrase: "[통화]의 환율은 얼마에요?" },
  {
    meaningId: 77,
    languageCode: "ko-KR",
    phrase: "추천하는 쇼핑 스폿이 어디에요?",
  },
  { meaningId: 78, languageCode: "ko-KR", phrase: "대사관에 가야 합니다." },
  { meaningId: 79, languageCode: "ko-KR", phrase: "영어 메뉴가 있나요?" },
  { meaningId: 80, languageCode: "ko-KR", phrase: "관심 없어요." },
  { meaningId: 81, languageCode: "ko-KR", phrase: "버스는 어디서 타나요?" },
  { meaningId: 82, languageCode: "ko-KR", phrase: "조금 더 천천히 말해 주세요." },
  {
    meaningId: 83,
    languageCode: "ko-KR",
    phrase: "[관광지]로 가는 최적의 방법은 뭐에요?",
  },
  { meaningId: 84, languageCode: "ko-KR", phrase: "같은 걸 주문합니다." },
  { meaningId: 85, languageCode: "ko-KR", phrase: "역으로 어떻게 가나요?" },
  { meaningId: 86, languageCode: "ko-KR", phrase: "근처에 공중 전화가 있나요?" },
  { meaningId: 87, languageCode: "ko-KR", phrase: "기분이 나빠요." },
  {
    meaningId: 88,
    languageCode: "ko-KR",
    phrase: "호텔까지 최적의 방법은 뭐에요?",
  },
  {
    meaningId: 89,
    languageCode: "ko-KR",
    phrase: "좀 더 크게 말씀해 주시겠어요?",
  },
  { meaningId: 90, languageCode: "ko-KR", phrase: "[장소]를 찾고 있어요." },
  { meaningId: 91, languageCode: "ko-KR", phrase: "Wi-Fi 비밀번호가 뭐에요?" },
  {
    meaningId: 92,
    languageCode: "ko-KR",
    phrase: "창가 좌석으로 앉을 수 있을까요?",
  },
  { meaningId: 93, languageCode: "ko-KR", phrase: "이거 맛있어요!" },
  { meaningId: 94, languageCode: "ko-KR", phrase: "추천하는 호텔이 어디에요?" },
  {
    meaningId: 95,
    languageCode: "ko-KR",
    phrase: "중심지로 가는 최적의 방법은 뭐에요?",
  },
  { meaningId: 96, languageCode: "ko-KR", phrase: "[음료] 한 잔 주세요." },
  { meaningId: 97, languageCode: "ko-KR", phrase: "엘리베이터가 있나요?" },
  { meaningId: 98, languageCode: "ko-KR", phrase: "추가 이불 주시겠어요?" },
  { meaningId: 99, languageCode: "ko-KR", phrase: "내일 날씨 예보는 어때요?" },
  { meaningId: 100, languageCode: "ko-KR", phrase: "도와주셔서 감사합니다." },
  */
];
